name: First Action

on: 
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Debug
        required: false
        default: false
      sample_value:
        type: string
        description: Sample Value
        required: true
        default: ''

jobs:
  hello_world:
    runs-on: ubuntu-latest
    
    steps:
      - name: First Step 
        run: echo "Hello World!"

      - name: Step 2
        run: echo "Hello Worls 2!"

  job2:
    runs-on: ubuntu-latest
    needs: hello_world
    steps:
      - name: First Step 
        run: echo "Hello World!"

      - name: Step 2
        run: echo "Hello Worls 2!"