name: First Action

on: 
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Step 1
        run: echo "Hello from Job 1 - Step 1"

      - name: Step 2
        run: echo "Hello from Job 1 - Step 2"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Step 1
        run: echo "Hello from Job 2 - Step 1"

      - name: Step 2
        run: echo "Hello from Job 2 - Step 2"