name : Second Action

on: 
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: 'Debug'
        required: false
        default: false
    sample_value:
        type: string
        description: 'Sample Value'
        required: true
        default: ''